# Generated by Django 2.1.1 on 2023-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230122_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='students', to='school.Teacher'),
        ),
    ]
