# Generated by Django 2.1.1 on 2023-01-22 11:45

from django.db import migrations


def make_many_teachers(apps, schema_editor):
    Student = apps.get_model('school', 'Student')

    for student in Student.objects.all():
        student.teachers.add(student.teacher)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_teachers'),
    ]

    operations = [
        migrations.RunPython(make_many_teachers),
    ]
