# Generated by Django 2.1.1 on 2023-01-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_change_teacher_to_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
