# Generated by Django 4.1.5 on 2023-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0002_alter_phone_image_alter_phone_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
